---
go: &go
  - "**/*.go"
  - "go.mod"
  - "go.sum"
  - "Makefile"

go_all:
  - *go

python: &python
  - "**/*.py"
  - "pyproject.toml"
  - "uv.lock"

python_all:
  - *python

yaml: &yaml
  - "**/*.yml"
  - "**/*.yaml"
  - "!docs/node_modules/**"
  - "!docs/pnpm-lock.yaml"

yaml_all:
  - *yaml

markdown: &markdown
  - "**/*.md"
  - "**/*.mdx"
  - "!docs/node_modules/**"

markdown_all:
  - *markdown

documentation: &documentation
  - "docs/**"
  - "!docs/node_modules/**"
  - ".vale.ini"
  - ".vale/**"

documentation_all:
  - *documentation

nix: &nix
  - "flake.nix"
  - "flake.lock"
  - "go.mod"
  - "go.sum"

nix_all:
  - *nix
