---
# Repository Labels Configuration
# Managed by crazy-max/ghaction-github-labeler

- name: bug
  color: d73a4a
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: go
  color: 00ADD8
  description: Go code changes

- name: ci
  color: 6f42c1
  description: CI/CD related changes

- name: backup
  color: fbca04
  description: Backup tool changes

- name: taskmanager
  color: 5319e7
  description: Task manager tool changes

- name: dependencies
  color: 0366d6
  description: Dependency updates

- name: security
  color: ee0701
  description: Security related changes

- name: breaking-change
  color: b60205
  description: Breaking change requiring attention

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
